name: Deploy Angular to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js version 20 explicitly
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Clear npm cache to avoid picking up old Node
      - name: Clean npm cache
        run: npm cache clean --force

      # Install dependencies using npm ci
      - name: Install dependencies
        run: npm ci

      # Build Angular app using local Angular CLI
      - name: Build Angular app
        run: npx ng build --configuration production

      # Deploy to Firebase
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
